"""Generate migration/setup_neon.sql from the LIVE Supabase data.

Pulls the three views from Supabase's REST API, escapes everything correctly
(apostrophes doubled, booleans as true/false, NULLs, the 2 Storage image_urls
rewritten to repo-relative paths), and sandwiches the INSERTs between the
schema DDL (01_schema.sql) and the anonymous-role grants (02_grants.sql).

Run:  python migration/generate_setup.py
Output: migration/setup_neon.sql  (paste once into the Neon Console SQL Editor)
"""
import json, os, urllib.request

SUPABASE = "https://esanxehwfmiktwmxzzrv.supabase.co/rest/v1"
ANON = "sb_publishable_MOlcKwFGCBaXhMtKiDOafw_wWHdvsl-"
HERE = os.path.dirname(os.path.abspath(__file__))


def fetch(table, order=None):
    url = f"{SUPABASE}/{table}?select=*&limit=10000"
    if order:
        url += f"&order={order}"
    req = urllib.request.Request(
        url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"}
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def lit(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def inserts(table, cols, rows, transform=None):
    lines = []
    for row in rows:
        if transform:
            row = transform(dict(row))
        vals = ", ".join(lit(row.get(c)) for c in cols)
        lines.append(f"insert into public.{table} ({', '.join(cols)}) values ({vals});")
    return "\n".join(lines)


def fix_img(row):
    u = row.get("image_url")
    if u and "supabase.co/storage" in u:
        row["image_url"] = f"images/{row['id']}.jpeg"
    return row


chars = fetch("ha_characters", "sort_order")
upgrades = fetch("ha_upgrades", "sort_order")
awak = fetch("ha_character_awakenings")

schema = open(os.path.join(HERE, "01_schema.sql"), encoding="utf-8").read().strip()
grants = open(os.path.join(HERE, "02_grants.sql"), encoding="utf-8").read().strip()

parts = [
    "-- GENERATED by generate_setup.py — do not edit by hand.",
    "-- Run ONCE in the Neon Console SQL Editor (schema + data + anonymous grants).",
    "",
    "begin;",
    "",
    "-- ===== SCHEMA =====",
    schema,
    "",
    "-- ===== DATA (pulled live from Supabase) =====",
    inserts("ha_characters",
            ["id", "name", "heirloom_name", "heirloom_type", "points", "level",
             "image_url", "sort_order", "created_at"], chars, fix_img),
    "",
    inserts("ha_upgrades",
            ["id", "name", "tier", "min_level", "cost", "repeatable",
             "requirements_note", "effect", "sort_order"], upgrades),
    "",
    inserts("ha_character_awakenings",
            ["character_id", "upgrade_id", "count", "taken_at"], awak),
    "",
    "-- ===== GRANTS =====",
    grants,
    "",
    "-- Tell the Data API's PostgREST to re-read the schema so the new tables show up:",
    "notify pgrst, 'reload schema';",
    "",
    "commit;",
    "",
]

out = os.path.join(HERE, "setup_neon.sql")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(parts))
print(f"chars={len(chars)} upgrades={len(upgrades)} awakenings={len(awak)}")
print("wrote", out)
