-- GENERATED by generate_setup.py — do not edit by hand.
-- Run ONCE in the Neon Console SQL Editor (schema + data + anonymous grants).

begin;

-- ===== SCHEMA =====
-- Heirloom Awakenings — Neon schema
-- Run this on your Neon project's database (the branch where the Data API is enabled).
--
-- Tables live directly in `public` and keep the `ha_` prefix so the existing
-- client calls (`db.from('ha_characters')` etc.) work unchanged. On a dedicated
-- Neon project the prefix is vestigial, but keeping it means zero diff in index.html.

create table if not exists public.ha_characters (
  id            uuid primary key default gen_random_uuid(),
  name          text        not null,
  heirloom_name text        not null,
  heirloom_type text        not null default 'Weapon',
  points        integer     not null default 6,
  level         integer     not null default 1,
  image_url     text,
  sort_order    integer     default 0,
  created_at    timestamptz default now()
);

create table if not exists public.ha_upgrades (
  id                text primary key,
  name              text    not null,
  tier              integer not null default 1,
  min_level         integer not null default 1,
  cost              integer not null default 1,
  repeatable        boolean not null default false,
  requirements_note text,
  effect            text    not null,
  sort_order        integer default 0
);

create table if not exists public.ha_character_awakenings (
  character_id uuid not null references public.ha_characters(id) on delete cascade,
  upgrade_id   text not null references public.ha_upgrades(id),
  count        integer not null default 1,
  taken_at     timestamptz default now(),
  primary key (character_id, upgrade_id)
);

-- ===== DATA (pulled live from Supabase) =====
insert into public.ha_characters (id, name, heirloom_name, heirloom_type, points, level, image_url, sort_order, created_at) values ('4dffd277-c40f-4964-932a-93ec2628d471', 'Gator', 'The Ticket', 'Accessory', 10, 12, 'https://www.dndbeyond.com/avatars/48413/893/1581111423-144386757.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp', 0, '2026-03-06T01:22:17.159838+00:00');
insert into public.ha_characters (id, name, heirloom_name, heirloom_type, points, level, image_url, sort_order, created_at) values ('9a77328e-2338-4188-ae0d-de8841d845a3', 'Lilith Blackwood', 'Nails of the Expanse', 'Accessory', 10, 12, 'https://www.dndbeyond.com/avatars/51664/35/1581111423-152733413.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp', 0, '2026-03-06T01:23:55.583989+00:00');
insert into public.ha_characters (id, name, heirloom_name, heirloom_type, points, level, image_url, sort_order, created_at) values ('2f6ddfab-e268-4a93-834c-c01671548e7c', 'Till', 'Hearthfire Glass Shades', 'Accessory', 10, 12, 'https://www.dndbeyond.com/avatars/52055/38/1581111423-152732854.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp', 0, '2026-03-06T01:25:39.589891+00:00');
insert into public.ha_characters (id, name, heirloom_name, heirloom_type, points, level, image_url, sort_order, created_at) values ('1f2a3b4b-1df5-4313-af85-65750649417e', 'Herbert', 'Dirt Jar', 'Accessory', 0, 12, 'images/1f2a3b4b-1df5-4313-af85-65750649417e.jpeg', 1, '2026-05-16T22:29:41.843619+00:00');
insert into public.ha_characters (id, name, heirloom_name, heirloom_type, points, level, image_url, sort_order, created_at) values ('f992a56e-a587-4f2c-bb55-5aef9aced0ea', 'Tessa', 'The Obsidian Ring', '', 10, 12, 'images/f992a56e-a587-4f2c-bb55-5aef9aced0ea.jpeg', 1, '2026-05-29T21:43:12.53342+00:00');

insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('duelist_level_1_t1', 'Duelist (level 1)', 1, 1, 2, true, 'Melee weapons', 'As a reaction when hit by a melee attack you see, add +1 to your AC.', 1);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('enhanced_weapon_level_1_t1', 'Enhanced Weapon (level 1)', 1, 1, 3, true, NULL, 'Gain a +1 bonus to attack and damage rolls made with this weapon.', 2);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('infusion_level_1_t1', 'Infusion (level 1)', 1, 1, 5, true, NULL, 'Choose a damage type (e.g., Fire, Force, Radiant); deal an additional d6 damage of that type.', 3);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('magical_core_level_1_t1', 'Magical Core (level 1)', 1, 1, 2, true, NULL, 'Choose a cantrip to cast from the weapon twice per long rest (+4 attack, DC 12).', 4);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('magus_level_1_t1', 'Magus (level 1)', 1, 1, 5, true, NULL, 'Gain a +1 bonus to spell attack rolls and a +1 bonus to AC while holding the weapon.', 5);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('slayer_level_1_t1', 'Slayer (level 1)', 1, 1, 5, true, NULL, 'Choose an enemy type (e.g., Undead, Fey); deal 2d6 additional damage to that type.', 6);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_link_level_1_t1', 'Spell Link (level 1)', 1, 1, 2, true, 'Spellcasters', 'Gain one additional level 1 spell slot, which refreshes on a long rest.', 7);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_storing_level_1_t1', 'Spell Storing (level 1)', 1, 1, 2, true, NULL, 'Choose a level 1 spell to cast from the weapon once per long rest (+4 attack, DC 12).', 8);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_storing_level_2_t1', 'Spell Storing (level 2)', 1, 1, 4, true, NULL, 'Choose a level 2 spell to cast from the weapon once per long rest (+4 attack, DC 12).', 9);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('bully_t1', 'Bully', 1, 1, 1, false, NULL, 'Gain advantage on Charisma (Intimidation) checks while holding the weapon.', 10);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('charmward_t1', 'Charmward', 1, 1, 1, false, NULL, 'Gain advantage on saving throws against being charmed.', 11);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('darkvision_t1', 'Darkvision', 1, 1, 3, false, NULL, 'Gain 60ft darkvision (or increase existing range by 60ft).', 12);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('deathward_t1', 'Deathward', 1, 1, 1, false, NULL, 'Gain advantage on death saving throws.', 13);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('fearward_t1', 'Fearward', 1, 1, 1, false, NULL, 'Gain advantage on saving throws against being frightened.', 14);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('focus_t1', 'Focus', 1, 1, 2, false, 'Spellcasters', 'The weapon counts as a spellcasting focus.', 15);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('giant_bane_t1', 'Giant-Bane', 1, 1, 4, false, NULL, 'Deal an additional d6 damage to creatures of Large size or larger.', 16);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('gripped_t1', 'Gripped', 1, 1, 1, false, NULL, 'You cannot be forced to drop this weapon against your will.', 17);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('guiding_t1', 'Guiding', 1, 1, 1, false, NULL, 'Weapon sheds bright light (15ft) and dim light (15ft) in a color of your choice.', 18);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('hidden_t1', 'Hidden', 1, 1, 2, false, NULL, 'Action to make the weapon appear as a different item; DC 12 Investigation to see through.', 19);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('hinge_bane_t1', 'Hinge-Bane', 1, 1, 1, false, 'Melee weapons', 'Deal maximum damage against inanimate objects.', 20);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('indomitable_level_1_t1', 'Indomitable (level 1)', 1, 1, 1, false, NULL, 'If reduced to 0 HP, use reaction to make one attack before falling unconscious.', 21);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('jarring_level_1_t1', 'Jarring (level 1)', 1, 1, 2, false, NULL, 'Damaged enemies cannot make opportunity attacks against you until your next turn.', 22);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('marksman_t1', 'Marksman', 1, 1, 3, false, 'Ranged weapons', 'Weapon requires no physical ammo; creates spectral magical ammo instead.', 23);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('overpower_brawler_t1', 'Overpower (Brawler)', 1, 1, 2, false, NULL, 'On a roll of 19-20, target makes DC 14 Str save or is knocked prone.', 24);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('overpower_brutish_t1', 'Overpower (Brutish)', 1, 1, 1, false, NULL, 'On a roll of 19-20, target makes DC 14 Str save or is shoved 10 feet.', 25);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('overpower_disarming_t1', 'Overpower (Disarming)', 1, 1, 2, false, NULL, 'On a roll of 19-20, target makes DC 14 Str save or drops a held item.', 26);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('overpower_dread_t1', 'Overpower (Dread)', 1, 1, 2, false, NULL, 'On a roll of 19-20, target makes DC 14 Wis save or is frightened for 1 minute.', 27);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('overpower_hamstring_t1', 'Overpower (Hamstring)', 1, 1, 1, false, NULL, 'On a roll of 19-20, target makes DC 14 Dex save or speed is halved.', 28);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('overpower_poisonous_t1', 'Overpower (Poisonous)', 1, 1, 2, false, NULL, 'On a roll of 19-20, target makes DC 14 Con save or is poisoned.', 29);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('poisonward_t1', 'Poisonward', 1, 1, 1, false, NULL, 'Gain advantage on saving throws against being poisoned.', 30);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('proficient_level_1_t1', 'Proficient (level 1)', 1, 1, 2, false, NULL, 'Gain proficiency in one skill of your choice.', 31);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('quick_t1', 'Quick', 1, 1, 3, false, NULL, 'Gain advantage on initiative rolls.', 32);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('ritualist_t1', 'Ritualist', 1, 1, 1, false, NULL, 'Time to ritual cast spells is halved while holding the weapon.', 33);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('shadowed_t1', 'Shadowed', 1, 1, 1, false, NULL, 'When in cover, you count the cover as one degree higher (e.g., 1/2 becomes 3/4).', 34);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('unflinching_t1', 'Unflinching', 1, 1, 1, false, 'Ranged attacks', 'Hostile creatures within 5ft do not impose disadvantage on your ranged attacks.', 35);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('willing_t1', 'Willing', 1, 1, 1, false, NULL, 'Declare before rolling to add 1d4 to a skill check (once per long rest).', 36);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('amplify_level_1_t2', 'Amplify (level 1)', 2, 5, 5, true, NULL, 'You gain a +1 bonus to an ability score of your choice (maximum of 20).', 37);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('duelist_level_2_t2', 'Duelist (level 2)', 2, 5, 4, true, 'Melee weapons', 'As a reaction when hit by a melee attack you see, you add +2 to your AC.', 38);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('enhanced_weapon_level_2_t2', 'Enhanced Weapon (level 2)', 2, 5, 6, true, NULL, 'You gain a +2 bonus to attack and damage rolls made with this weapon.', 39);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('guardian_level_1_t2', 'Guardian (level 1)', 2, 5, 4, true, NULL, 'You gain proficiency in a saving throw of your choice.', 40);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('keen_level_1_t2', 'Keen (level 1)', 2, 5, 4, true, NULL, 'The weapon scores a critical hit on a d20 roll of 19 or 20.', 41);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('magical_core_level_2_t2', 'Magical Core (level 2)', 2, 5, 4, true, NULL, 'Choose a cantrip to cast at will from the weapon as an action (+4 spell attack, DC 14).', 42);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_link_level_2_t2', 'Spell Link (level 2)', 2, 5, 4, true, 'Spellcasters', 'You gain one additional level 2 spell slot, which refreshes on a long rest.', 43);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_storing_level_3_t2', 'Spell Storing (level 3)', 2, 5, 6, true, NULL, 'Choose a level 3 spell to cast from the weapon once per long rest (+6 spell attack, DC 14).', 44);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('stern_t2', 'Stern', 2, 5, 4, true, 'Heavy weapon', 'At the start of your turn, gain +2 AC and reduced movement (0) until your next turn; no reactions allowed.', 45);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('barbaric_t2', 'Barbaric', 2, 5, 2, false, NULL, 'Gain advantage on your next attack after reducing a creature to 0 hit points.', 46);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('battlemage_t2', 'Battlemage', 2, 5, 4, false, 'Spellcasters', 'When you cast a spell, you can use a bonus action to make a weapon attack.', 47);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('blindside_level_1_t2', 'Blindside (level 1)', 2, 5, 4, false, 'Rogues', 'Increase your sneak attack damage with this weapon by 1d6.', 48);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('bolstering_t2', 'Bolstering', 2, 5, 2, false, NULL, 'Regain extra hit points equal to your Constitution modifier when healed by a spell.', 49);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('challenge_t2', 'Challenge', 2, 5, 4, false, 'Barbarians', 'Nominate one creature; they do not gain advantage against your Reckless Attack until your next turn.', 50);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('charged_smite_level_1_t2', 'Charged Smite (level 1)', 2, 5, 2, false, 'Paladins', 'Deal an additional 1d8 radiant damage when using Divine Smite.', 51);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('distracting_level_1_t2', 'Distracting (level 1)', 2, 5, 2, false, 'Ranged weapons', 'After an action attack, move up to half speed without provoking opportunity attacks.', 52);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('divine_grace_t2', 'Divine Grace', 2, 5, 2, false, 'Clerics', 'Commune for 10 minutes to reroll any one die within 24 hours (refreshes on rest).', 53);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('divine_touch_t2', 'Divine Touch', 2, 5, 4, false, 'Cleric/Druid/Paladin', 'First time you deal melee damage each turn, an ally within 5ft heals 1d4.', 54);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('doomerang_t2', 'Doomerang', 2, 5, 3, false, NULL, 'Gain the thrown trait; weapon returns at end of turn, hitting those in its path (DC 10 Dex, 1d6 damage).', 55);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('en_guard_t2', 'En Guard', 2, 5, 3, false, 'Fighters', 'Use reaction when you or nearby ally is attacked for various combat buffs (refreshes on rest).', 56);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('eye_of_the_storm_t2', 'Eye of the Storm', 2, 5, 5, false, 'Monks', 'Use an action to restore ki points equal to half your monk level (once per long rest).', 57);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('guard_t2', 'Guard', 2, 5, 4, false, 'Melee weapons', 'Use reaction to impose disadvantage on a weapon attack targeting an ally within 5ft.', 58);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('hunter_s_watch_t2', 'Hunter’s Watch', 2, 5, 3, false, 'Rangers', 'Reaction attack at 30ft; hit creature makes DC 14 Dex save or speed becomes 0 (refreshes on rest).', 59);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('jarring_level_2_t2', 'Jarring (level 2)', 2, 5, 4, false, NULL, 'Enemies you attack cannot make attacks of opportunity against you until your next turn.', 60);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('mobile_level_1_t2', 'Mobile (level 1)', 2, 5, 3, false, NULL, 'Your base movement speed increases by 5 feet.', 61);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('piercing_level_1_t2', 'Piercing (level 1)', 2, 5, 3, false, NULL, 'Gain +2 on attack rolls against enemies using shields.', 62);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('power_of_the_ancestors_t2', 'Power of the Ancestors', 2, 5, 4, false, 'Sorcerers', 'Once per day, use sorcery points without expending them.', 63);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('precise_level_1_t2', 'Precise (level 1)', 2, 5, 2, false, NULL, 'You can reroll damage results of 1 (must accept second result).', 64);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('proficient_level_2_t2', 'Proficient (level 2)', 2, 5, 4, false, NULL, 'You gain proficiency in 2 skills of your choice.', 65);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('quickshot_t2', 'Quickshot', 2, 5, 4, false, 'Ranged weapons', 'First hit on your turn grants advantage on the next attack that turn.', 66);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('rampaging_t2', 'Rampaging', 2, 5, 3, false, 'Melee weapons', 'Gain advantage on attacks if you began your turn over 20 feet from the target.', 67);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('reckless_t2', 'Reckless', 2, 5, 4, false, NULL, 'When you have advantage, you can reroll your damage dice (must accept second result).', 68);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('reverberation_t2', 'Reverberation', 2, 5, 5, false, 'Bards', 'Expend inspiration on attack; target makes Wis save or is charmed or frightened.', 69);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('scout_t2', 'Scout', 2, 5, 2, false, NULL, 'Gain advantage on attacks during the first round of combat.', 70);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('sniping_t2', 'Sniping', 2, 5, 3, false, 'Ranged weapons', 'Target''s cover counts as one degree lower (e.g., 3/4 becomes 1/2).', 71);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spellhunter_t2', 'Spellhunter', 2, 5, 5, false, NULL, 'Attacks deal an additional 2d6 psychic damage against spellcasters.', 72);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('sprightly_t2', 'Sprightly', 2, 5, 2, false, NULL, 'Use bonus action for advantage on next attack (refreshes on rest if hit).', 73);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('telepathic_link_t2', 'Telepathic Link', 2, 5, 3, false, NULL, 'Communicate telepathically with a familiar creature within 60 feet you can see.', 74);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('transforming_t2', 'Transforming', 2, 5, 2, false, NULL, 'Action to turn weapon into a mundane version; command word restores it.', 75);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('transposed_t2', 'Transposed', 2, 5, 2, false, NULL, 'Bonus action to summon or dismiss the weapon to a pocket dimension.', 76);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('trapped_spell_t2', 'Trapped Spell', 2, 5, 4, false, 'Warlocks', 'Store one known spell per long rest to release as a bonus action (no slot/components).', 77);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('underhanded_t2', 'Underhanded', 2, 5, 2, false, NULL, 'Reaction to cause disadvantage on a melee attack (refreshes on rest if attack misses).', 78);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('vicious_level_1_t2', 'Vicious (level 1)', 2, 5, 2, false, NULL, 'On a natural 20, critical hits deal an extra 2d6 damage.', 79);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('wild_spell_t2', 'Wild Spell', 2, 5, 3, false, 'Druids', 'Expend a slot during Wild Shape to ready and cast a spell while transformed.', 80);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('will_of_the_ancestors_t2', 'Will of the Ancestors', 2, 5, 4, false, NULL, 'Action for 15ft AoE; enemies make DC 14 Wis save or take 2d8 psychic damage (refreshes on rest)', 81);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('duelist_level_3_t3', 'Duelist (level 3)', 3, 10, 6, true, 'Melee weapons', 'As a reaction when hit by a melee attack you see, add +3 to your AC.', 82);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('enhanced_weapon_level_3_t3', 'Enhanced Weapon (level 3)', 3, 10, 10, true, NULL, 'Gain a +3 bonus to attack and damage rolls made with this weapon.', 83);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('flying_t3', 'Flying', 3, 10, 6, true, NULL, 'You gain a flying speed equal to your current movement speed.', 84);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('infusion_level_2_t3', 'Infusion (level 2)', 3, 10, 10, true, NULL, 'Choose a damage type; your weapon attacks deal an additional 2d6 damage of that type.', 85);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('magical_core_level_3_t3', 'Magical Core (level 3)', 3, 10, 6, true, NULL, 'Choose a level 1 spell; cast it from the weapon twice per long rest (+8 attack, DC 16).', 86);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('magus_level_2_t3', 'Magus (level 2)', 3, 10, 8, true, NULL, 'While holding the weapon, gain +2 to spell attack rolls and +2 to AC.', 87);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_link_level_3_t3', 'Spell Link (level 3)', 3, 10, 6, true, 'Spellcasters', 'Gain one additional level 3 spell slot, which refreshes on a long rest.', 88);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spell_storing_level_4_t3', 'Spell Storing (level 4)', 3, 10, 8, true, NULL, 'Choose a level 4 spell; cast it from the weapon once per long rest (+8 attack, DC 16).', 89);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('blindside_level_2_t3', 'Blindside (level 2)', 3, 10, 8, false, 'Rogues', 'Increase your sneak attack damage with this weapon by 2d6.', 90);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('blood_drinker_level_1_t3', 'Blood-Drinker (level 1)', 3, 10, 5, false, NULL, 'On a roll of 19-20, gain temporary hit points equal to half the damage dealt.', 91);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('brawn_t3', 'Brawn', 3, 10, 3, false, NULL, 'You cannot be knocked prone and have advantage on grapple checks.', 92);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('charged_smite_level_2_t3', 'Charged Smite (level 2)', 3, 10, 4, false, 'Paladins', 'Deal an additional 2d8 radiant damage when using Divine Smite.', 93);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('distracting_level_2_t3', 'Distracting (level 2)', 3, 10, 4, false, 'Ranged weapons', 'Take attack action; move up to half speed before the attack without provoking opportunity attacks.', 94);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('elemental_manipulation_t3', 'Elemental Manipulation', 3, 10, 5, false, NULL, 'When casting a damage-dealing spell with a slot, you can substitute the damage type for another.', 95);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('elemental_resistance_t3', 'Elemental Resistance', 3, 10, 4, false, NULL, 'Choose a damage type (e.g., Fire, Force); you gain resistance to that type.', 96);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('focused_t3', 'Focused', 3, 10, 4, false, NULL, 'Choose an ability score; damaged enemies have disadvantage on saves for that score until your next turn.', 97);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('hardy_t3', 'Hardy', 3, 10, 3, false, NULL, 'Action: spend up to half your hit dice to recover health (once per long rest).', 98);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('indomitable_level_2_t3', 'Indomitable (level 2)', 3, 10, 3, false, NULL, 'If reduced to 0 HP, immediately take the Attack action before falling unconscious.', 99);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('lashing_t3', 'Lashing', 3, 10, 4, false, NULL, 'When making an opportunity attack, make an additional attack (no ability modifier to damage).', 100);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('nemesis_t3', 'Nemesis', 3, 10, 4, false, NULL, 'Nominate a creature; attacks deal an extra 2d8 psychic damage against them (1-week cooldown to change).', 101);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('proficient_level_3_t3', 'Proficient (level 3)', 3, 10, 6, false, NULL, 'You gain proficiency in 3 skills of your choice.', 102);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('rapid_strike_t3', 'Rapid Strike', 3, 10, 4, false, NULL, 'Use bonus action after an attack to make an extra attack vs a different target (*4 SP Melee / 6 SP Ranged).', 103);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('shimmering_t3', 'Shimmering', 3, 10, 4, false, NULL, 'Ranged attacks against you have disadvantage if you are within 5ft of another creature.', 104);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spelleater_t3', 'Spelleater', 3, 10, 3, false, NULL, 'Use reaction to make an attack of opportunity against a creature casting a spell within 5ft.', 105);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spellhunter_t3', 'Spellhunter', 3, 10, 5, false, NULL, 'Concentration checks caused by this weapon''s damage are made at disadvantage.', 106);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('sustaining_t3', 'Sustaining', 3, 10, 3, false, NULL, 'You do not need to eat, drink, or sleep while in possession of the weapon.', 107);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('tracking_t3', 'Tracking', 3, 10, 2, false, NULL, 'Action: learn the exact direction of a creature damaged by this weapon in the last week (10-mile range).', 108);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('will_level_1_t3', 'Will (level 1)', 3, 10, 3, false, NULL, 'You can reroll a failed concentration check once per long rest.', 109);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('blindside_level_2_t4', 'Blindside (level 2)', 4, 15, 8, true, 'Rogues', 'Increase your sneak attack damage with this weapon by 2d6.', 110);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('blood_drinker_level_1_t4', 'Blood-Drinker (level 1)', 4, 15, 5, true, NULL, 'On a roll of 19-20, gain temporary hit points equal to half the damage dealt.', 111);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('brawn_t4', 'Brawn', 4, 15, 3, true, NULL, 'You cannot be knocked prone and have advantage on grapple checks.', 112);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('charged_smite_level_2_t4', 'Charged Smite (level 2)', 4, 15, 4, true, 'Paladins', 'Deal an additional 2d8 radiant damage when using Divine Smite.', 113);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('distracting_level_2_t4', 'Distracting (level 2)', 4, 15, 4, true, 'Ranged weapons', 'Take attack action; move up to half speed before the attack without provoking opportunity attacks.', 114);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('elemental_manipulation_t4', 'Elemental Manipulation', 4, 15, 5, true, NULL, 'When casting a damage-dealing spell with a slot, you can substitute the damage type for another.', 115);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('elemental_resistance_t4', 'Elemental Resistance', 4, 15, 4, true, NULL, 'Choose a damage type (e.g., Fire, Force); you gain resistance to that type.', 116);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('focused_t4', 'Focused', 4, 15, 4, true, NULL, 'Choose an ability score; damaged enemies have disadvantage on saves for that score until your next turn.', 117);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('hardy_t4', 'Hardy', 4, 15, 3, true, NULL, 'Action: spend up to half your hit dice to recover health (once per long rest).', 118);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('indomitable_level_2_t4', 'Indomitable (level 2)', 4, 15, 3, true, NULL, 'If reduced to 0 HP, immediately take the Attack action before falling unconscious.', 119);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('lashing_t4', 'Lashing', 4, 15, 4, true, NULL, 'When making an opportunity attack, make an additional attack (no ability modifier to damage).', 120);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('nemesis_t4', 'Nemesis', 4, 15, 4, true, NULL, 'Nominate a creature; attacks deal an extra 2d8 psychic damage against them (1-week cooldown to change).', 121);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('proficient_level_3_t4', 'Proficient (level 3)', 4, 15, 6, true, NULL, 'You gain proficiency in 3 skills of your choice.', 122);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('rapid_strike_t4', 'Rapid Strike', 4, 15, 4, true, NULL, 'Use bonus action after an attack to make an extra attack vs a different target (*4 SP Melee / 6 SP Ranged).', 123);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('shimmering_t4', 'Shimmering', 4, 15, 4, true, NULL, 'Ranged attacks against you have disadvantage if you are within 5ft of another creature.', 124);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spelleater_t4', 'Spelleater', 4, 15, 3, true, NULL, 'Use reaction to make an attack of opportunity against a creature casting a spell within 5ft.', 125);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spellhunter_t4', 'Spellhunter', 4, 15, 5, true, NULL, 'Concentration checks caused by this weapon''s damage are made at disadvantage.', 126);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('sustaining_t4', 'Sustaining', 4, 15, 3, true, NULL, 'You do not need to eat, drink, or sleep while in possession of the weapon.', 127);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('tracking_t4', 'Tracking', 4, 15, 2, true, NULL, 'Action: learn the exact direction of a creature damaged by this weapon in the last week (10-mile range).', 128);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('will_level_1_t4', 'Will (level 1)', 4, 15, 3, true, NULL, 'You can reroll a failed concentration check once per long rest.', 129);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('beacon_t4', 'Beacon', 4, 15, 5, false, NULL, 'Action to plant weapon; for 1 minute, allies within 15ft gain +1 AC and +d6 force damage.', 130);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('blood_drinker_level_2_t4', 'Blood-Drinker (level 2)', 4, 15, 7, false, NULL, 'On a roll of 19-20, you gain temporary hit points equal to the damage dealt.', 131);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('dancing_t4', 'Dancing', 4, 15, 5, false, 'Melee weapons', 'Action to let weapon fight independently for 1 minute; control it with a bonus action.', 132);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('homing_t4', 'Homing', 4, 15, 5, false, 'Ranged weapons', 'Attack targets without line of sight (at disadvantage); targets count as being in 3/4 cover.', 133);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('mentor_t4', 'Mentor', 4, 15, 3, false, 'Spellcasters', 'Cast any known spell (even if not prepared) by expending your highest available slot (1/day).', 134);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('mobile_level_2_t4', 'Mobile (level 2)', 4, 15, 7, false, NULL, 'Your base movement speed increases by 10 feet.', 135);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('piercing_level_2_t4', 'Piercing (level 2)', 4, 15, 5, false, NULL, 'You gain +4 on attack rolls against enemies using shields.', 136);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('power_surge_t4', 'Power Surge', 4, 15, 5, false, NULL, 'Once per day, use a spell slot to cast a known spell up to 2 levels higher than the slot used.', 137);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('precise_level_2_t4', 'Precise (level 2)', 4, 15, 6, false, NULL, 'You can reroll any damage results from this weapon (must accept second result).', 138);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('proficient_level_4_t4', 'Proficient (level 4)', 4, 15, 4, false, NULL, 'You gain proficiency in 4 skills of your choice.', 139);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('protective_t4', 'Protective', 4, 15, 3, false, NULL, 'You can make one saving throw at advantage per short or long rest.', 140);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('rallying_t4', 'Rallying', 4, 15, 4, false, NULL, 'Action: Allies within 30ft gain advantage on Wis saves and immunity to frightened for 1 minute.', 141);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('spectral_reach_t4', 'Spectral Reach', 4, 15, 5, false, NULL, 'Action: Increase range by 5ft and deal +d4 damage for 1 minute (refreshes on rest).', 142);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('venomous_t4', 'Venomous', 4, 15, 7, false, NULL, 'Target must succeed DC 15 Con save or take 2d6 poison damage at the start of their round.', 143);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('vicious_level_2_t4', 'Vicious (level 2)', 4, 15, 4, false, NULL, 'On a natural 20, critical hits deal an extra 4d6 damage.', 144);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('whirlwind_t4', 'Whirlwind', 4, 15, 5, false, NULL, 'Use an action to make a melee attack against every creature within 5 feet.', 145);
insert into public.ha_upgrades (id, name, tier, min_level, cost, repeatable, requirements_note, effect, sort_order) values ('will_level_2_t4', 'Will (level 2)', 4, 15, 5, false, 'Spellcasters', 'When you fail a concentration check, you can choose to pass it instead (1/day).', 146);

insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('4dffd277-c40f-4964-932a-93ec2628d471', 'indomitable_level_1_t1', 1, '2026-03-06T02:05:02.518376+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('4dffd277-c40f-4964-932a-93ec2628d471', 'hinge_bane_t1', 1, '2026-03-06T02:05:11.230753+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('4dffd277-c40f-4964-932a-93ec2628d471', 'fearward_t1', 1, '2026-03-06T02:05:17.48271+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('4dffd277-c40f-4964-932a-93ec2628d471', 'deathward_t1', 1, '2026-03-06T02:05:24.751229+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('2f6ddfab-e268-4a93-834c-c01671548e7c', 'blindside_level_2_t3', 1, '2026-03-07T02:40:54.285068+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('9a77328e-2338-4188-ae0d-de8841d845a3', 'magus_level_2_t3', 1, '2026-03-07T02:41:51.384674+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('9a77328e-2338-4188-ae0d-de8841d845a3', 'proficient_level_1_t1', 1, '2026-03-07T02:45:41.659932+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('2f6ddfab-e268-4a93-834c-c01671548e7c', 'proficient_level_1_t1', 1, '2026-03-07T02:47:55.766598+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('4dffd277-c40f-4964-932a-93ec2628d471', 'flying_t3', 1, '2026-03-09T23:53:02.548644+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('f992a56e-a587-4f2c-bb55-5aef9aced0ea', 'overpower_brawler_t1', 1, '2026-05-30T00:42:08.415642+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('f992a56e-a587-4f2c-bb55-5aef9aced0ea', 'jarring_level_1_t1', 1, '2026-05-30T00:42:10.499948+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('f992a56e-a587-4f2c-bb55-5aef9aced0ea', 'brawn_t3', 1, '2026-05-30T00:44:11.824545+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('f992a56e-a587-4f2c-bb55-5aef9aced0ea', 'vicious_level_1_t2', 1, '2026-05-30T00:45:59.057727+00:00');
insert into public.ha_character_awakenings (character_id, upgrade_id, count, taken_at) values ('f992a56e-a587-4f2c-bb55-5aef9aced0ea', 'gripped_t1', 1, '2026-05-30T00:47:14.210138+00:00');

-- ===== GRANTS =====
-- Heirloom Awakenings — Neon Data API access control
--
-- This app has no login. Every request reaches the Data API WITHOUT an
-- Authorization header, so it runs as the built-in `anonymous` role.
-- Today on Supabase the equivalent is the anon key + permissive RLS = fully
-- public read/write. We reproduce that here with table GRANTs + RLS left OFF.
--
-- Run this AFTER 01_schema.sql, and after the Data API is enabled on the branch
-- (enabling it creates the `anonymous` role). If you ticked "Grant public schema
-- access" when enabling the Data API, the first GRANTs may already be in place —
-- re-running them is harmless.

grant usage on schema public to anonymous;

grant select, insert, update, delete
  on public.ha_characters, public.ha_upgrades, public.ha_character_awakenings
  to anonymous;

-- Future tables in public also get access (so later migrations don't need a re-grant):
alter default privileges in schema public
  grant select, insert, update, delete on tables to anonymous;

-- RLS is intentionally left disabled on these tables: the app is public by design,
-- so there is no per-row owner to filter on. If you later add user accounts, enable
-- RLS here and add policies instead of relying on the anonymous GRANTs above.

-- Tell the Data API's PostgREST to re-read the schema so the new tables show up:
notify pgrst, 'reload schema';

commit;
